repos:
  - repo: https://github.com/asottile/reorder_python_imports
    rev: v2.5.0
    hooks:
      - id: reorder-python-imports

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.1
    hooks:
      - id: flake8
        args: ["--ignore=E501,W292", "--max-line-length=119"]
        # additional_dependencies:
        #   - flake8-bugbear==21.3.2
        #   - flake8-builtins==1.5.3
        #   - pep8-naming==0.11.1
        #   - flake8-variables-names==0.0.2

  - repo: https://github.com/psf/black
    rev: 21.4b2
    hooks:
      - id: black
        args: ["--line-length=119"]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: check-json
      - id: check-xml
      - id: check-yaml
      - id: detect-private-key
      - id: requirements-txt-fixer
      - id: end-of-file-fixer
        exclude: ^data/
      - id: trailing-whitespace
        args: ["--markdown-linebreak-ext=md"]
